/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.table.DefaultTableModel;
import master.alternatif;
import master.kriteria;
import master.bobot_kriteria;
import ahp.ahp;
import ahp.hasil;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import database.database;
import java.sql.SQLException;
/**
 *
 * @author imam
 */
public class proses extends javax.swing.JFrame {
    alternatif alternatif;
    kriteria kriteria;
    bobot_kriteria bbt_kriteria;
    ahp ahp;
    hasil hsl;
    Connection con;
    Statement stm;
    ResultSet rs;
    database db;
    
    String[][] hasil = null;
    
    public DefaultTableModel modelTbAlternatif;
    String[] headerTbAlternatif = {"No","Nama", "Penyampaian Materi", "Test", "Pemahaman Siswa", "Cara Belajar", "Kenyamanan"};
    public DefaultTableModel modelTbHasil;
    String[] headerTbHasil = {"No", "Nama", "Hasil"};
    public DefaultTableModel modelTbKriteria;
    /**
     * Creates new form proses
     */
    public proses() {
        initComponents();
        awal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAlternatif = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKriteria = new javax.swing.JTable();
        btnProses = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbHasil = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Alternatif");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 452, -1));

        tbAlternatif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbAlternatif);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 36, -1, 407));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Perbandingan Kriteria");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 12, 452, -1));

        tbKriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbKriteria);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 36, -1, 407));

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, 320, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hasil");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(962, 12, 321, -1));

        tbHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbHasil);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(962, 36, 321, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        hasil = ahp.hitung_ahp();
        hsl.save(hasil);
        tampilHasil();
    }//GEN-LAST:event_btnProsesActionPerformed

    private void awal(){
        db = new database();
        alternatif = new alternatif();
        kriteria = new kriteria();
        bbt_kriteria = new bobot_kriteria();
        ahp = new ahp();
        hsl = new hasil();
        modelTbAlternatif = new DefaultTableModel(null, headerTbAlternatif);
        tbAlternatif.setModel(modelTbAlternatif);
        modelTbHasil = new DefaultTableModel(null, headerTbHasil);
        tbHasil.setModel(modelTbHasil);
        tampilAlternatif();
        tampilKriteria();
    }
    
    private void tampilAlternatif(){
        String[][] data_alternatif = alternatif.get_all();
        modelTbAlternatif.getDataVector().removeAllElements();
        modelTbAlternatif.fireTableDataChanged();
        for (int i = 0; i < data_alternatif.length; i++) {
            Object[] ob = new Object[data_alternatif[i].length];
            ob[0] = i+1;
            System.arraycopy(data_alternatif[i], 1, ob, 1, data_alternatif[i].length - 1);
            modelTbAlternatif.addRow(ob);
        }
    }
    
    private void tampilKriteria(){
        String[][] data_kriteria = kriteria.get_all();
        String[][] data_bbt_kriteria = bbt_kriteria.pak();
        String[] headerTbKriteria = new String[data_kriteria.length + 2];
        headerTbKriteria[0] = "No";
        headerTbKriteria[1] = "Nama";
        for (int i = 2; i < headerTbKriteria.length; i++) {
            headerTbKriteria[i] = data_kriteria[i - 2][1];
        }
        modelTbKriteria = new DefaultTableModel(null, headerTbKriteria);
        modelTbKriteria.getDataVector().removeAllElements();
        modelTbKriteria.fireTableDataChanged();
        tbKriteria.setModel(modelTbKriteria);
        for (int i = 0; i < data_kriteria.length; i++) {
            Object[] ob = new Object[headerTbKriteria.length];
            ob[0] = i+1;
            ob[1] = data_kriteria[i][1];
            for (int j = 0; j < data_bbt_kriteria[0].length; j++) {
                ob[j+2] = data_bbt_kriteria[i][j];
            }
            modelTbKriteria.addRow(ob);
        }
    }
    
    private void tampilHasil(){
        int kolom = tbHasil.getColumnCount();
        modelTbHasil.getDataVector().removeAllElements();
        modelTbHasil.fireTableDataChanged();
        String sql = "SELECT nama_alternatif, hasil FROM `hasil`, alternatif WHERE hasil.kode_alternatif=alternatif.kode_alternatif ORDER BY hasil DESC";
        try {
            con = db.getKoneksi();
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            int no = 1;
            while(rs.next()){
                Object[] ob = new Object[kolom];
                ob[0] = no++;
                for (int i = 1; i < ob.length; i++) {
                    ob[i] = rs.getString(i);
                }
                modelTbHasil.addRow(ob);
            }
            con.close(); stm.close(); rs.close();
        } catch (SQLException e) {
            System.out.println("error : "+e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbAlternatif;
    private javax.swing.JTable tbHasil;
    private javax.swing.JTable tbKriteria;
    // End of variables declaration//GEN-END:variables
}
